datos = [
    {
        "Afghanistan": "0.52",
        "Albania": "0.04",
        "Algeria": "0.56",
        "American Samoa": "0",
        "Andorra": "0",
        "Angola": "0.45",
        "Anguilla": "0",
        "Antigua and Barbuda": "0",
        "Argentina": "0.57",
        "Armenia": "0.03",
        "Aruba": "0",
        "Australia": "0.33",
        "Austria": "0.11",
        "Azerbaijan": "0.13",
        "Bahamas": "0.01",
        "Bahrain": "0.02",
        "Bangladesh": "2.15",
        "Barbados": "0",
        "Belarus": "0.12",
        "Belgium": "0.15",
        "Belize": "0.01",
        "Benin": "0.17",
        "Bermuda": "0",
        "Bhutan": "0.01",
        "Bolivia": "0.15",
        "Bosnia and Herzegovina": "0.04",
        "Botswana": "0.03",
        "Brazil": "2.7",
        "British Virgin Islands": "0",
        "Brunei": "0.01",
        "Bulgaria": "0.09",
        "Burkina Faso": "0.28",
        "Burundi": "0.16",
        "Cambodia": "0.21",
        "Cameroon": "0.35",
        "Canada": "0.48",
        "Cape Verde": "0.01",
        "Cayman Islands": "0",
        "Central African Republic": "0.07",
        "Chad": "0.22",
        "Chile": "0.25",
        "China": "17.88",
        "Colombia": "0.65",
        "Comoros": "0.01",
        "Cook Islands": "0",
        "Costa Rica": "0.06",
        "Croatia": "0.05",
        "Cuba": "0.14",
        "Curacao": "0",
        "Cyprus": "0.02",
        "Czech Republic": "0.13",
        "Denmark": "0.07",
        "Djibouti": "0.01",
        "Dominica": "0",
        "Dominican Republic": "0.14",
        "DR Congo": "1.24",
        "Ecuador": "0.23",
        "Egypt": "1.39",
        "El Salvador": "0.08",
        "Equatorial Guinea": "0.02",
        "Eritrea": "0.05",
        "Estonia": "0.02",
        "Eswatini": "0.02",
        "Ethiopia": "1.55",
        "Falkland Islands": "0",
        "Faroe Islands": "0",
        "Fiji": "0.01",
        "Finland": "0.07",
        "France": "0.81",
        "French Guiana": "0",
        "French Polynesia": "0",
        "Gabon": "0.03",
        "Gambia": "0.03",
        "Georgia": "0.05",
        "Germany": "1.05",
        "Ghana": "0.42",
        "Gibraltar": "0",
        "Greece": "0.13",
        "Greenland": "0",
        "Grenada": "0",
        "Guadeloupe": "0",
        "Guam": "0",
        "Guatemala": "0.22",
        "Guernsey": "0",
        "Guinea": "0.17",
        "Guinea-Bissau": "0.03",
        "Guyana": "0.01",
        "Haiti": "0.15",
        "Honduras": "0.13",
        "Hong Kong": "0.09",
        "Hungary": "0.12",
        "Iceland": "0",
        "India": "17.77",
        "Indonesia": "3.45",
        "Iran": "1.11",
        "Iraq": "0.56",
        "Ireland": "0.06",
        "Isle of Man": "0",
        "Israel": "0.11",
        "Italy": "0.74",
        "Ivory Coast": "0.35",
        "Jamaica": "0.04",
        "Japan": "1.55",
        "Jersey": "0",
        "Jordan": "0.14",
        "Kazakhstan": "0.24",
        "Kenya": "0.68",
        "Kiribati": "0",
        "Kuwait": "0.05",
        "Kyrgyzstan": "0.08",
        "Laos": "0.09",
        "Latvia": "0.02",
        "Lebanon": "0.07",
        "Lesotho": "0.03",
        "Liberia": "0.07",
        "Libya": "0.09",
        "Liechtenstein": "0",
        "Lithuania": "0.03",
        "Luxembourg": "0.01",
        "Macau": "0.01",
        "Madagascar": "0.37",
        "Malawi": "0.26",
        "Malaysia": "0.43",
        "Maldives": "0.01",
        "Mali": "0.28",
        "Malta": "0.01",
        "Marshall Islands": "0",
        "Martinique": "0",
        "Mauritania": "0.06",
        "Mauritius": "0.02",
        "Mayotte": "0",
        "Mexico": "1.6",
        "Micronesia": "0",
        "Moldova": "0.04",
        "Monaco": "0",
        "Mongolia": "0.04",
        "Montenegro": "0.01",
        "Montserrat": "0",
        "Morocco": "0.47",
        "Mozambique": "0.41",
        "Myanmar": "0.68",
        "Namibia": "0.03",
        "Nauru": "0",
        "Nepal": "0.38",
        "Netherlands": "0.22",
        "New Caledonia": "0",
        "New Zealand": "0.07",
        "Nicaragua": "0.09",
        "Niger": "0.33",
        "Nigeria": "2.74",
        "Niue": "0",
        "North Korea": "0.33",
        "North Macedonia": "0.03",
        "Northern Mariana Islands": "0",
        "Norway": "0.07",
        "Oman": "0.06",
        "Pakistan": "2.96",
        "Palau": "0",
        "Palestine": "0.07",
        "Panama": "0.06",
        "Papua New Guinea": "0.13",
        "Paraguay": "0.09",
        "Peru": "0.43",
        "Philippines": "1.45",
        "Poland": "0.5",
        "Portugal": "0.13",
        "Puerto Rico": "0.04",
        "Qatar": "0.03",
        "Republic of the Congo": "0.07",
        "Reunion": "0.01",
        "Romania": "0.25",
        "Russia": "1.81",
        "Rwanda": "0.17",
        "Saint Barthelemy": "0",
        "Saint Kitts and Nevis": "0",
        "Saint Lucia": "0",
        "Saint Martin": "0",
        "Saint Pierre and Miquelon": "0",
        "Saint Vincent and the Grenadines": "0",
        "Samoa": "0",
        "San Marino": "0",
        "Sao Tome and Principe": "0",
        "Saudi Arabia": "0.46",
        "Senegal": "0.22",
        "Serbia": "0.09",
        "Seychelles": "0",
        "Sierra Leone": "0.11",
        "Singapore": "0.07",
        "Sint Maarten": "0",
        "Slovakia": "0.07",
        "Slovenia": "0.03",
        "Solomon Islands": "0.01",
        "Somalia": "0.22",
        "South Africa": "0.75",
        "South Korea": "0.65",
        "South Sudan": "0.14",
        "Spain": "0.6",
        "Sri Lanka": "0.27",
        "Sudan": "0.59",
        "Suriname": "0.01",
        "Sweden": "0.13",
        "Switzerland": "0.11",
        "Syria": "0.28",
        "Taiwan": "0.3",
        "Tajikistan": "0.12",
        "Tanzania": "0.82",
        "Thailand": "0.9",
        "Timor-Leste": "0.02",
        "Togo": "0.11",
        "Tokelau": "0",
        "Tonga": "0",
        "Trinidad and Tobago": "0.02",
        "Tunisia": "0.15",
        "Turkey": "1.07",
        "Turkmenistan": "0.08",
        "Turks and Caicos Islands": "0",
        "Tuvalu": "0",
        "Uganda": "0.59",
        "Ukraine": "0.5",
        "United Arab Emirates": "0.12",
        "United Kingdom": "0.85",
        "United States": "4.24",
        "United States Virgin Islands": "0",
        "Uruguay": "0.04",
        "Uzbekistan": "0.43",
        "Vanuatu": "0",
        "Vatican City": "0",
        "Venezuela": "0.35",
        "Vietnam": "1.23",
        "Wallis and Futuna": "0",
        "Western Sahara": "0.01",
        "Yemen": "0.42",
        "Zambia": "0.25",
        "Zimbabwe": "0.2",
    }
]
